version: '3'

services:
  db_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookingquerymsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    hostname: mysql
    volumes:
      - mysql8-data:/var/lib/mysql
      - ./ops/docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  axonserver:
    image: 'axoniq/axonserver:latest'
    environment:
      - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
    ports:
      - '8024:8024'
      - '8124:8124'

volumes:
  mysql8-data: