version: '3'

services:
  db_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookingmsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    hostname: mysql
    volumes:
      - mysql8-data:/var/lib/mysql
      - ./ops/docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  mysql8-data:
